generate:
  folder: generated # Folder to which save generated code from current dir
  contracts:
    - file: ./contracts/eosio.json # Path to ABI JSON file
      name_override: eosio123 # Contract name override, it will be used for get_table_rows and Action builder
    - file: /some/folder/contracts/eosio.json
      name_override: eosio123
