package ts

import "strings"

var ClientTemplate = strings.TrimSpace(`
// Generated by eos-abigen-js version {{.Version}}
import {JsonRpc} from "eosjs";
import * as types from "./types";

export class Client {
    rpc: JsonRpc;

    public constructor(opts: types.ClientOpts) {
        this.rpc = opts.rpc;
    }
    {{ range .Methods }}
    public async {{.MethodName}}(params?: types.GetTableRowsParams): Promise<types.{{.ReturnName}}> {
        let lower_bound = params?.lower_bound || params?.bounds || undefined;
        let upper_bound = params?.upper_bound || params?.bounds || undefined;
        return await this.rpc.get_table_rows({
            json: true,
            code: params?.code || types.CONTRACT_NAME,
            scope: params?.scope || types.CONTRACT_NAME,
            table: "{{.TableName}}",
            lower_bound: lower_bound,
            upper_bound: upper_bound,
            index_position: params?.index_position,
            key_type: params?.key_type,
            limit: params?.limit,
            reverse: params?.reverse,
            show_payer: params?.show_payer,
        })
    }
    {{end}}
}
`)
