package ts

import "strings"

var TypesTemplate = strings.TrimSpace(`// Generated by eos-abigen-js version {{.Version}}

import {JsonRpc} from "eosjs";

export const CONTRACT_NAME = "{{.ContractName}}";

export interface ClientOpts {
    rpc: JsonRpc;
}

export type GetTableRowsParams = Partial<{
    code: string
    scope: string
    bounds: string
    lower_bound: string
    upper_bound: string
    index_position: number
    key_type: string
    limit: number
    reverse: boolean
    show_payer: boolean
}>

{{ if ne .StructTypes nil }} {{ .StructTypes }} {{ end }}
{{ if ne .RowTypes nil }} {{ .RowTypes }} {{ end }}
`)
